<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dfrobot_pirate">

  <xacro:include filename="$(find dfrobot_robots)/urdf/common.xacro" />

  <xacro:property name="base_plate_length" value="0.2" />
  <xacro:property name="base_plate_height" value="0.04" />
  <xacro:property name="base_plate_width" value="${0.18-2*wheel_width}" />

  <xacro:property name="spacer_length" value="0.06" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_plate_length} ${base_plate_width} ${base_plate_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_plate_length} ${base_plate_width} ${base_plate_height}"/>
      </geometry>
    </collision> 
  </link>

  <link name="top_plate">
    <visual>
      <geometry>
        <box size="${base_plate_length} ${base_plate_width+wheel_width} 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_plate_length} ${base_plate_width+wheel_width} 0.001"/>
      </geometry>
    </collision> 
  </link>  

  <joint name="top_plate_to_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="top_plate"/>
    <origin rpy="0 0 0" xyz="0 0 ${spacer_length+base_plate_height/2}"/>
  </joint>

  <joint name="controlboard_to_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="control_board"/>
    <origin rpy="0 0 0" xyz="-0.03 0 ${base_plate_height/2 + 0.002}"/>
  </joint>

  <xacro:macro name="spacer" params="suffix *origin">
    <link name="spacer_${suffix}">
      <visual>
        <geometry>
          <cylinder length="${spacer_length}" radius="0.003"/>
        </geometry>
        <material name="silver"/>
      </visual>
    </link>

    <joint name="base_to_spacer${suffix}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="spacer_${suffix}"/>
      <xacro:insert_block name="origin" />
    </joint>
  </xacro:macro>

  <xacro:spacer suffix="front_left">
    <origin rpy="0 0 0" xyz="${base_plate_length/2 - 0.02} ${base_plate_width/2 - 0.01} ${(base_plate_height+spacer_length)/2}"/>
  </xacro:spacer>
  <xacro:spacer suffix="front_right">
    <origin rpy="0 0 0" xyz="${base_plate_length/2 - 0.02} ${-(base_plate_width/2 - 0.01)} ${(base_plate_height+spacer_length)/2}"/>
  </xacro:spacer>
  <xacro:spacer suffix="rear_left">
    <origin rpy="0 0 0" xyz="${-(base_plate_length/2 - 0.02)} ${base_plate_width/2 - 0.01} ${(base_plate_height+spacer_length)/2}"/>
  </xacro:spacer>
  <xacro:spacer suffix="rear_right">
    <origin rpy="0 0 0" xyz="${-(base_plate_length/2 - 0.02)} ${-(base_plate_width/2 - 0.01)} ${(base_plate_height+spacer_length)/2}"/>
  </xacro:spacer>

  <xacro:wheel suffix="front_left" parent="base_link">
    <origin rpy="${-pi/2}  0 0" xyz="${base_plate_length/2 - 0.015} ${base_plate_width/2+wheel_width/2} 0"/>
  </xacro:wheel>
  <xacro:wheel suffix="front_right"  parent="base_link">
    <origin rpy="${-pi/2} 0 0" xyz="${base_plate_length/2 - 0.015} ${-(base_plate_width/2+wheel_width/2)} 0"/>
  </xacro:wheel>
  <xacro:wheel suffix="rear_left" parent="base_link">
    <origin rpy="${-pi/2}  0 0" xyz="${-base_plate_length/2 + 0.015} ${base_plate_width/2+wheel_width/2} 0"/>
  </xacro:wheel>
  <xacro:wheel suffix="rear_right"  parent="base_link">
    <origin rpy="${-pi/2} 0 0" xyz="${-base_plate_length/2 + 0.015} ${-(base_plate_width/2+wheel_width/2)} 0"/>
  </xacro:wheel>

</robot>
