<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dfrobot_turtle">

  <xacro:include filename="$(find dfrobot_robots)/urdf/common.xacro" />

  <xacro:property name="base_plate_radius" value="0.085" />
  <xacro:property name="base_plate_height" value="0.055" />
  <xacro:property name="caster_ball_radius" value="0.01" />

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_plate_height}" radius="${base_plate_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_plate_height}" radius="${base_plate_radius}"/>
      </geometry>
    </collision> 
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="controlboard_to_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="control_board"/>
    <origin rpy="0 0 0" xyz="-0.03 0 ${base_plate_height/2 + 0.002}"/>
  </joint>
  
  <xacro:wheel suffix="right" parent="base_link" >
    <origin rpy="${-pi/2}  0 0" xyz="-0.025 ${-1*(base_plate_radius-wheel_width/2)} ${-2*caster_ball_radius}"/>
  </xacro:wheel>
  <xacro:wheel suffix="left"  parent="base_link">
    <origin rpy="${-pi/2} 0 0" xyz="-0.025 ${(base_plate_radius-wheel_width/2)}    ${-2*caster_ball_radius}"/>
  </xacro:wheel>

  <link name="caster_housing">
    <visual>
      <geometry>
          <cylinder length="${caster_ball_radius}" radius="${caster_ball_radius}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
          <cylinder length="${caster_ball_radius}" radius="${caster_ball_radius}"/>
      </geometry>
    </collision> 
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link> 

  <gazebo reference="caster_housing">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_to_caster_housing_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_housing"/>
      <origin rpy="0 0 0" xyz="${base_plate_radius-caster_ball_radius-0.005} 0 ${-base_plate_height/2 - caster_ball_radius/2}"/>
  </joint>

  <link name="caster_ball">
    <visual>
      <geometry>
        <sphere radius="${caster_ball_radius}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_ball_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial> 
  </link> 

  <gazebo reference="caster_ball">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_to_caster_ball_joint" type="continuous">
      <parent link="caster_housing"/>
      <child link="caster_ball"/>
      <axis xyz="0 1 0"/>
      <origin rpy="0 0 0" xyz="0 0 ${-caster_ball_radius/2}"/>
  </joint>

</robot>
